using System.Text.Json.Serialization;

namespace Vinstag.InstagramAPI.Models.UserById;


public record User(
    [property: JsonPropertyName("pk")] long Pk,
    [property: JsonPropertyName("username")] string Username,
    [property: JsonPropertyName("full_name")] string FullName,
    [property: JsonPropertyName("is_private")] bool IsPrivate,
    [property: JsonPropertyName("profile_pic_url")] string ProfilePicUrl,
    [property: JsonPropertyName("profile_pic_id")] string ProfilePicId,
    [property: JsonPropertyName("is_verified")] bool IsVerified,
    [property: JsonPropertyName("follow_friction_type")] int FollowFrictionType,
    [property: JsonPropertyName("has_anonymous_profile_picture")] bool HasAnonymousProfilePicture,
    [property: JsonPropertyName("media_count")] int MediaCount,
    [property: JsonPropertyName("geo_media_count")] int GeoMediaCount,
    [property: JsonPropertyName("follower_count")] int FollowerCount,
    [property: JsonPropertyName("following_count")] int FollowingCount,
    [property: JsonPropertyName("following_tag_count")] int FollowingTagCount,
    [property: JsonPropertyName("is_supervision_features_enabled")] bool IsSupervisionFeaturesEnabled,
    [property: JsonPropertyName("biography")] string Biography,
    [property: JsonPropertyName("external_url")] string ExternalUrl,
    [property: JsonPropertyName("show_fb_link_on_profile")] bool ShowFbLinkOnProfile,
    [property: JsonPropertyName("primary_profile_link_type")] int PrimaryProfileLinkType,
    [property: JsonPropertyName("total_igtv_videos")] int TotalIgtvVideos,
    [property: JsonPropertyName("has_igtv_series")] bool HasIgtvSeries,
    [property: JsonPropertyName("has_videos")] bool HasVideos,
    [property: JsonPropertyName("total_clips_count")] int TotalClipsCount,
    [property: JsonPropertyName("total_ar_effects")] int TotalArEffects,
    [property: JsonPropertyName("usertags_count")] int UsertagsCount,
    [property: JsonPropertyName("is_favorite")] bool IsFavorite,
    [property: JsonPropertyName("is_favorite_for_stories")] bool IsFavoriteForStories,
    [property: JsonPropertyName("is_favorite_for_highlights")] bool IsFavoriteForHighlights,
    [property: JsonPropertyName("is_interest_account")] bool IsInterestAccount,
    [property: JsonPropertyName("has_chaining")] bool HasChaining,
    [property: JsonPropertyName("mutual_followers_count")] int MutualFollowersCount,
    [property: JsonPropertyName("profile_context")] string ProfileContext,
    [property: JsonPropertyName("has_highlight_reels")] bool HasHighlightReels,
    [property: JsonPropertyName("has_guides")] bool HasGuides,
    [property: JsonPropertyName("can_be_reported_as_fraud")] bool CanBeReportedAsFraud,
    [property: JsonPropertyName("is_business")] bool IsBusiness,
    [property: JsonPropertyName("professional_conversion_suggested_account_type")] int ProfessionalConversionSuggestedAccountType,
    [property: JsonPropertyName("account_type")] int AccountType,
    [property: JsonPropertyName("is_call_to_action_enabled")] object IsCallToActionEnabled,
    [property: JsonPropertyName("interop_messaging_user_fbid")] long InteropMessagingUserFbid,
    [property: JsonPropertyName("has_primary_country_in_feed")] bool HasPrimaryCountryInFeed,
    [property: JsonPropertyName("has_primary_country_in_profile")] bool HasPrimaryCountryInProfile,
    [property: JsonPropertyName("include_direct_blacklist_status")] bool IncludeDirectBlacklistStatus,
    [property: JsonPropertyName("is_potential_business")] bool IsPotentialBusiness,
    [property: JsonPropertyName("show_post_insights_entry_point")] bool ShowPostInsightsEntryPoint,
    [property: JsonPropertyName("request_contact_enabled")] bool RequestContactEnabled,
    [property: JsonPropertyName("is_bestie")] bool IsBestie,
    [property: JsonPropertyName("show_account_transparency_details")] bool ShowAccountTransparencyDetails,
    [property: JsonPropertyName("auto_expand_chaining")] bool AutoExpandChaining,
    [property: JsonPropertyName("highlight_reshare_disabled")] bool HighlightReshareDisabled,
    [property: JsonPropertyName("is_memorialized")] bool IsMemorialized,
    [property: JsonPropertyName("open_external_url_with_in_app_browser")] bool OpenExternalUrlWithInAppBrowser,
    [property: JsonPropertyName("has_exclusive_posts")] bool HasExclusivePosts
);